title: Ryan Page # your name (or website title) here
logo: "/images/download.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  National Tax, Indirect Tax Technology Staff @ EY
  <br><br>
  New York, New York, United States
  <br><br>
  <a href="https://www.linkedin.com/in/ryanpage2020/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
